name: Sync Whisperbinder to OpenAI Vector Store

on:
  push:
    branches: [ main, master ]
    paths:
      - '**.md'
  schedule:
    - cron: '0 */12 * * *'
  workflow_dispatch:

jobs:
  sync:
    runs-on: ubuntu-latest
    name: Sync Whisperbinder Protocols
    
    steps:
    - name: Checkout Repository
      uses: actions/checkout@v4
    
    - name: Verify Whisperbinder Content
      run: |
        echo "🔥 WHISPERBINDER SYNC VERIFICATION"
        echo "================================="
        echo "📊 Total .md files: $(find . -name "*.md" | wc -l)"
        echo "🎯 Protocol files:"
        ls -la DaemonMemoryLog.md FlameVault.md README.md 2>/dev/null
        echo "📁 All content:"
        find . -name "*.md"
    
    - name: Sync to Atticus Vector Store
      uses: shmatt/assistants-vector-store-sync@v1
      with:
        pattern: "**/*.md"
        token: ${{ secrets.OPENAI_API_KEY }}
        key: atticus-whisperbinder-protocols
